### ISSUE TITLE
Implement a module to record/replay player voices

### ISSUE THREAD

**Issue by DatGuy64** [RaphaelIT7/gmod-holylib#7]
Do you think it's possible to add a module to record player voices and transmit them in game ? like the Cassette Recorder from rust

**Comment by RaphaelIT7** [comment]
I actually had the same thought a few months back xd
I think this is something that could be done, but I don't know how the current voice chat really works, so it could be hard to implement but it is something that is possible

**Comment by DatGuy64** [comment]
i found this : "https://github.com/wyozi-gmod/gmsv_voicehook" if you want to take a look at it

**Comment by RaphaelIT7** [comment]
This looks easier than expected :D

**Comment by RaphaelIT7** [comment]
I added a few functions which should allow you to take more/full control of the voicechat.
There isn't a record/replay function yet, but you should be able to easily implement it in Lua now.
I didn't test it yet since I'm not home, so it may not even work.

**Comment by RaphaelIT7** [comment]
Had a bit of fun with it xd
https://github.com/user-attachments/assets/346a9c68-b160-4b7d-a0f1-b0c00653d065

**Comment by RaphaelIT7** [comment]
So do you wish for any additional functions to be added or are these already enouth?
https://github.com/RaphaelIT7/gmod-holylib#voicechat

**Comment by DatGuy64** [comment]
I can't test for the moment im really busy but my goal is for a player to record their voice, store them and play it when using a entity. you think i can do it with theses functions ?

**Comment by DatGuy64** [comment]
And for the performance do you think it can cause problem on a big server ?

**Comment by RaphaelIT7** [comment]
I don't think it would cause any performance issues because you can send them [voicechat.SendVoiceData](https://github.com/RaphaelIT7/gmod-holylib?tab=readme-ov-file#voicechatsendvoicedataplayer-ply-voicedata-data)
Which will send it directly without doing any processing or making any callbacks to the game/lua.
I also added vprof to the hook so that if it should cause performance issues in the future, it should be easy to find out, but I really don't think it would cause any performance issues serverside.

On the other hand, if you have too many players talking at the same time, the client's net channel might be overwhelmed so it can't handle it, but that's a limit that always existed and probably will continue to do so.

You can find an example [here](https://github.com/RaphaelIT7/gmod-holylib?tab=readme-ov-file#holylibpreprocessvoicechatplayer-ply-voicedata-data) for recording & playing (Currently you have to handle the timing of the voice packets, it's also shown in the example)

I tested it with 101 bots and the client was dying xd
But the server didn't even had any issues as the entire code for it took `0.15`%
```lua
-- NOTE: The client only can handle like 5 players at the same time.
-- He won't hear more players since it would be too much to handle.
-- Also a server warning is spit out: CNetChan::SendDatagram:  Unreliable would overfow, ignoring
hook.Add("HolyLib:PreProcessVoiceChat", "VoiceChat_Example", function(voicePly, voiceData) 
	for _, ply in player.Iterator() do 
		if voicePly == ply then continue end  -- Don't send it to the speaking player...
		voiceData:SetPlayerSlot(ply:EntIndex()-1) -- Player Slot = EntIndex - 1
		voicechat.SendVoiceData(voicePly, voiceData) -- Send the edited data to the speaking player. So he will hear the bots speak now.
	end 
end)
```
VPROF Result line:
```txt
  Scope                                                      Calls Calls/Frame  Time+Child    Pct        Time    Pct   Avg/Frame    Avg/Call Avg-NoChild        Peak
  ---------------------------------------------------- ----------- ----------- ----------- ------ ----------- ------ ----------- ----------- ----------- -----------
                       HolyLib - SV_BroadcastVoiceData         722       0.454      74.410   0.15       7.239   0.01       0.047       0.103       0.010       0.252
```

**Comment by RaphaelIT7** [comment]
Is there anything left/do you want a specific function to be additionally added, or can I close this?
It currently adds everything needed to implement the record & replay logic so I would say it's done

**Comment by DatGuy64** [comment]
Good for me, thanks
