### ISSUE TITLE
Prediction problems

### ISSUE THREAD

**Issue by Dead0Duck** [RaphaelIT7/gmod-holylib#9]
Holylib version: 3 and 4
Server OS: Ubuntu 22.04
Gmod server version: Latest

I have prediction problems on holylib 3 (and 4), on collisions at a angle there is desync.
I've tried to disable surffix and other modules, but it isn't helped.
On holylib v2 there is no prediction problems and player collides with props as intended.

Video with Holylib 4 and prediction problems: https://youtu.be/h_oGJpHBGH0
Video with Holylib 2 and without prediction problems: https://youtu.be/NYulBkp0Wtw

Map from video (if needed): https://steamcommunity.com/sharedfiles/filedetails/?id=3331574445

**Comment by RaphaelIT7** [comment]
Can you try to disable the filesystem? 
holylib_enable_filesystem 0

My guess would be that the filesystem prediction fails and breaks something.

**Comment by Dead0Duck** [comment]
Yes, probably it is. I disabled filesystem with startup parameter and collision/prediction was fine

**Comment by RaphaelIT7** [comment]
I disabled `holylib_filesystem_predictexistance` by default now which should solve this.
Just put `holylib_filesystem_predictexistance 0` into your config and it should be solved.

It's caused by the models files being spread thru multiple folders.
So the `.mdl` is for example packed into the .bsp but then the `.vdd` is inside `garrsmod/models/`.
It internally just uses the searchpath of the `.mdl` to search for the `.vdd` and the other files.

**Comment by Dead0Duck** [comment]
Oh, thank you! I'm on vacation and just saw your message.
